<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Options;
use Symfony\Component\Cache\Adapter\RedisAdapter;

/**
 * OptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
