<?php

namespace AppBundle\Repository;

/**
 * PortfolioSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioSetRepository extends \Doctrine\ORM\EntityRepository
{
}
