imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: easy_admin.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    cache:
        app: cache.adapter.redis
        default_redis_provider: "redis://%redis_host%"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
      dicts: "@dictionary_manager"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    bundles: []
    assets:
        guest_css:
            inputs:
                - 'styles/main.css'
                - 'styles/menu.css'
                - 'styles/login_form.css'
                - 'styles/login_button.css'
                - 'styles/index.css'
                - 'styles/basket.css'
                - 'styles/portfolio.css'
                - 'styles/job.css'
        admin_css:
            inputs:
                - 'assets/vendor/dropzone/dist/min/dropzone.min.css'
                - 'styles/select2-bootstrap.css'
                - 'assets/vendor/select2/dist/css/select2.min.css'
        guest_js:
            inputs:
                - 'assets/vendor/jquery/dist/jquery.min.js'
                - 'assets/vendor/lodash/dist/lodash.min.js'
                - 'assets/vendor/vue-resource/dist/vue-resource.min.js'
                - 'assets/vendor/js-cookie/src/js.cookie.js'
                - 'assets/vendor/hammerjs/hammer.min.js'
                - 'assets/vendor/bootstrap-validator/dist/validator.min.js'
                - 'scripts/menu_basket.js'
                - 'scripts/menu.js'
                - 'scripts/basket.js'
                - 'scripts/portfolio.js'
                - 'scripts/jobs.js'
        admin_js:
            inputs:
                - 'assets/vendor/select2/dist/js/select2.js'
                - 'assets/vendor/dropzone/dist/min/dropzone.min.js'
    filters:
        cssrewrite: ~


fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

oneup_flysystem:
    adapters:
        upload_adapter:
            local:
                directory: "%kernel.root_dir%/../web/uploads"
    filesystems:
        upload_filesystem:
            adapter:    upload_adapter

vich_uploader:
    db_driver: orm
#    storage:   flysystem
    mappings:
        portfolio_images:
            uri_prefix:         /uploads/portfolio/images
            upload_destination: "%kernel.root_dir%/../web/uploads/portfolio/images"
#            upload_destination: upload_filesystem


liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [150, 150], mode: inset }
        big_thumb:
            quality: 75
            filters:
                thumbnail: { size: [1024, 1024], mode: inset }