app_web:
    resource: "@AppBundle/Web"
    type:     annotation

app_api:
    resource: "@AppBundle/Api"
    type:     annotation
    prefix: /api/v1/

app_privacy:
    path: /privacy
    defaults:
        _controller: FrameworkBundle:Template:template
        template: ':web/static:privacy.html.twig'


easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin



fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
