app_web:
    resource: "@AppBundle/Web"
    type:     annotation

app_api:
    resource: "@AppBundle/Api"
    type:     annotation
    prefix: /api/v1/

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
