# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    dictionary_manager:
        class: AppBundle\Services\DictionaryManager
        arguments: ['@router', '@doctrine', "@options_service", "@cache.app", "@request_stack"]
    options_service:
        class: AppBundle\Services\OptionsService
        arguments: ["@cache.app", "@doctrine"]
    basket_service:
        class: AppBundle\Services\BasketService
        arguments: ["@doctrine", '@mailer', '@templating', '@options_service']
    portfolio_service:
        class: AppBundle\Services\PortfolioService
        arguments: ["@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@router"]
    cache_invalidator:
        class: AppBundle\EventListener\CacheInvalidator
        arguments: ["@options_service", "@dictionary_manager"]
        tags:
            - {name: doctrine.event_subscriber, connection: default}
