###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

baikalfortit-memcached:
  image: phpdockerio/memcached:latest
  container_name: baikalfortit-memcached

baikalfortit-postgres:
  image: postgres:9.6
  container_name: baikalfortit-postgres
  environment:
    - POSTGRES_USER=mick
    - POSTGRES_PASSWORD=dj%0nJ]aacf9lbs
    - POSTGRES_DB=baikalfortit

baikalfortit-webserver:
  image: phpdockerio/nginx:latest
  container_name: baikalfortit-webserver
  volumes:
      - ..:/var/www/baikalfortit
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8081:80"
  links:
   - baikalfortit-php-fpm

baikalfortit-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: baikalfortit-php-fpm
  volumes:
    - ..:/var/www/baikalfortit
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - baikalfortit-memcached
    - baikalfortit-postgres
