- title: Монтажные работы
  items:
    - title: Монтаж и подключение видеокамеры
      unit: шт
      price: 1500
    - title: Установка и настройка видеорегистратора на 4 видеокамеры (устройство записи)
      unit:
      price: 1500
    - title: Установка и настройка видеорегистратора на 8 видеокамер (устройство записи)
      unit:
      price: 3000
    - title: Установка и настройка видеорегистратора на 16 видеокамер (устройство записи)
      unit:
      price: 4500
    - title: Установка разъема BNC(BNC-p)
      unit: шт
      price: 50
    - title: Подключение блока питания внутреннего
      unit: шт
      price: 450
    - title: Монтаж распределительной коробки
      unit: шт
      price: 50
    - title: Прокладка кабеля для видеосистем открытой проводкой
      unit: м
      price: 25
    - title: Прокладка кабеля для видеосистем в трубе (кабель-канале)
      unit: м
      price: 50
    - title: Пуско-наладка систем видеонаблюдения
      unit:
      price: 500
    - title: Настройка удаленного доступа
      unit:
      price: 2000
    - title: Транспортные расходы
      unit:
      price: 500


- title: Оборудование:
  items:
    - title: Видеорегистратор 4 канала
      unit:
      price: 3600
    - title: Видеорегистратор 8 каналов
      unit:
      price: 8000
    - title: Видеорегистратор 16 каналов
      unit:
      price: 11000
    - title: Видеокамера цветная AHD,уличная,с ИК подсветкой 1мп
      unit: шт
      price: 1800
    - title: Видеокамера цветная AHD,уличная,с ИК подсветкой 2мп
      unit: шт
      price: 2500
    - title: Кабель RG-59
      unit: м
      price: 25
    - title: Микрофон
      unit: м
      price: 400
    - title: Блок бесперебойного питания, Источник питания стабилизированный 12В,с возможностью автономной работы от АКБ 7А/ч
      unit: шт
      price: 1470
    - title: "Аккумулятор SF 1207, стационарный свинцово-кислотный, Емкость аккумулятора: 7 Ач"
      unit: шт
      price: 550
    - title: Жесткий диск на 30 (дней записи)
      unit: шт
      price: 3500
    - title: Жесткий диск на 60 (дней записи)
      unit: шт
      price: 5000